dict_title = {'appleinsider.ru': 'AppleInsider.ru — Все об Apple, iPhone, iPad, iPod, iMac, MacBook',
              'appleinsider.ru/page/2': 'AppleInsider.ru — Все об Apple, iPhone, iPad, iPod, iMac, MacBook',
              'appleinsider.ru/tags': 'Темы - AppleInsider.ru',
              'appleinsider.ru/macbook-pro': 'MacBook Pro MacBook Pro обзор и новости - AppleInsider.ru',
              'appleinsider.ru/macbook-pro/page/2': 'MacBook Pro MacBook Pro обзор и новости, cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/ios': 'iOS Новости iOS - AppleInsider.ru',
              'appleinsider.ru/ios/page/3': 'iOS Новости iOS, cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/iphone': 'iPhone обзоры и последние новости iPhone - AppleInsider.ru',
              'appleinsider.ru/iphone/page/3': 'iPhone обзоры и последние новости iPhone, cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/accessories': 'Аксессуары Обзоры аксессуаров Apple  - AppleInsider.ru',
              'appleinsider.ru/accessories/page/4': 'Аксессуары Обзоры аксессуаров Apple , cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/tag/prilozhenie': 'Приложения для Apple устройств - AppleInsider.ru',
              'appleinsider.ru/tag/prilozhenie/page/4': 'Приложения для Apple устройств, cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/tag/obzory-igrappleinsider.ru/tag/obzory-igr/page/2appleinsider.ru/tag/apple': '',
              'appleinsider.ru/tag/apple/page/2': 'Apple Компания Apple выпускает лучшую мобильную продукцию: iPhone, iPad, iPod, MacBook, cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/tag/obnovlenie': 'Обновление iOS и OS X, обзоры апдейтов ios - AppleInsider.ru',
              'appleinsider.ru/tag/obnovlenie/page/3': 'Обновление iOS и OS X, обзоры апдейтов ios, cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/tag/smartfony': 'Смартфоны Apple и других марок известных производителей - AppleInsider.ru',
              'appleinsider.ru/tag/smartfony/page/2': 'Смартфоны Apple и других марок известных производителей, cтраница %page% - AppleInsider.ru',
              'appleinsider.ru/authors': 'Авторы - AppleInsider.ru',
              'appleinsider.ru/author/svarogstin': '',
              'appleinsider.ru/author/svarogstin/page/2': '',
              'appleinsider.ru/author/gellert': '',
              'appleinsider.ru/author/gellert/page/3': '',
              'appleinsider.ru/author/maxways': '',
              'appleinsider.ru/author/maxways/page/4': '',
              'appleinsider.ru/author/appleinsider-ru': '',
              'appleinsider.ru/author/appleinsider-ru/page/2': '',
              'appleinsider.ru/macbook-pro/macbook-pro-mid-2014-xorosho-no-malo.html': 'MacBook Pro (Mid 2014): хорошо, но мало - AppleInsider.ru',
              'appleinsider.ru/accessories/prezentaciya-apple-watch-polet-na-lunu-i-drugie-istorii.html': 'Презентация Apple Watch, полет на Луну и другие истории - AppleInsider.ru',
              'appleinsider.ru/sudy-i-skandaly/huawei-propagandists.html': 'Даже пропагандисты Huawei предпочитают пользоваться iPhone - AppleInsider.ru',
              'appleinsider.ru/sudy-i-skandaly/na-tima-kuka-podali-v-sud-za-obman-investorov.html': 'На Тима Кука подали в суд за обман инвесторов - AppleInsider.ru',
              'appleinsider.ru/accessories/eto-samyj-treshovyj-aksessuar-dlya-iphone-kotoryj-my-videli.html': 'Это самый трешовый аксессуар для iPhone, который мы видели - AppleInsider.ru',
              'appleinsider.ru/advert': 'Рекламодателям - AppleInsider.ru',
              'appleinsider.ru/about': 'О сайте - AppleInsider.ru',
              'appleinsider.ru/podcastonair': 'podcastonair - AppleInsider.ru',
              'appleinsider.ru/discounts': 'discounts - AppleInsider.ru'}

dict_descr = {'appleinsider.ru': 'Обзор лучших приложений под iPhone, как отремонтировать iPhone или iPad, что нужно знать при покупке Mac и MacBook. Бесплатные приложения iOS и iPadOS.',
              'appleinsider.ru/page/2': 'Обзор лучших приложений под iPhone, как отремонтировать iPhone или iPad, что нужно знать при покупке Mac и MacBook. Бесплатные приложения iOS и iPadOS.',
              'appleinsider.ru/tags': '',
              'appleinsider.ru/macbook-pro': 'Если вы ищите мобильный компьютер, отличающийся производительностью мощной настольной машины, то MacBook Pro точно для вас. А если вы ищите интересную информ...',
              'appleinsider.ru/macbook-pro/page/2': 'Если вы ищите мобильный компьютер, отличающийся производительностью мощной настольной машины, то MacBook Pro точно для вас. А если вы ищите интересную информ...',
              'appleinsider.ru/ios': 'Откройте для себя целую вселенную iOS благодаря нашим свежим новостям и интересным обзорам! Ни одно обновление этой мобильной платформы не пройдет мимо вашег...',
              'appleinsider.ru/ios/page/3': 'Откройте для себя целую вселенную iOS благодаря нашим свежим новостям и интересным обзорам! Ни одно обновление этой мобильной платформы не пройдет мимо вашег...',
              'appleinsider.ru/iphone': 'iPhone – это не просто телефон, а совершенно новый взгляд на жизнь. Именно благодаря ему вся индустрия смартфонов притерпела значительные изменения. На сегод...',
              'appleinsider.ru/iphone/page/3': 'iPhone – это не просто телефон, а совершенно новый взгляд на жизнь. Именно благодаря ему вся индустрия смартфонов притерпела значительные изменения. На сегод...',
              'appleinsider.ru/accessories': 'Для техники Apple в мире придуманы и продаются миллионы различных аксессуаров:  начиная от тряпочек для экрана, заканчивая золотыми чехлами. Но как выбрать  ...',
              'appleinsider.ru/accessories/page/4': 'Для техники Apple в мире придуманы и продаются миллионы различных аксессуаров:  начиная от тряпочек для экрана, заканчивая золотыми чехлами. Но как выбрать  ...',
              'appleinsider.ru/tag/prilozhenie': 'На AppleInsider.ru вы найдете не только рассказы о новых и интересных приложениях, но и подробные текстовые и видеообзоры новинок App Store и Mac App Store....',
              'appleinsider.ru/tag/prilozhenie/page/4': 'На AppleInsider.ru вы найдете не только рассказы о новых и интересных приложениях, но и подробные текстовые и видеообзоры новинок App Store и Mac App Store....',
              'appleinsider.ru/tag/obzory-igrappleinsider.ru/tag/obzory-igr/page/2appleinsider.ru/tag/apple': '',
              'appleinsider.ru/tag/apple/page/2': 'Компания Apple, основанная в 1977 году, переживала множество взлетов и падений. Даже по прошествии всех этих лет наблюдать за ней не становится менее интерес...',
              'appleinsider.ru/tag/obnovlenie': 'Apple регулярно балует своих пользователей не только аппаратными, но и программными новинками. AppleInsider.ru оперативно делится информацией обо всех доступ...',
              'appleinsider.ru/tag/obnovlenie/page/3': 'Apple регулярно балует своих пользователей не только аппаратными, но и программными новинками. AppleInsider.ru оперативно делится информацией обо всех доступ...',
              'appleinsider.ru/tag/smartfony': 'До 2007 года «умные» телефоны на самом деле не были так умны. С появлением iPhone мы поняли, каким должен быть настоящий смартфон....',
              'appleinsider.ru/tag/smartfony/page/2': 'До 2007 года «умные» телефоны на самом деле не были так умны. С появлением iPhone мы поняли, каким должен быть настоящий смартфон....',
              'appleinsider.ru/authors': '',
              'appleinsider.ru/author/svarogstin': '',
              'appleinsider.ru/author/svarogstin/page/2': '',
              'appleinsider.ru/author/gellert': '', 'appleinsider.ru/author/gellert/page/3': '',
              'appleinsider.ru/author/maxways': '',
              'appleinsider.ru/author/maxways/page/4': '',
              'appleinsider.ru/author/appleinsider-ru': '',
              'appleinsider.ru/author/appleinsider-ru/page/2': '',
              'appleinsider.ru/macbook-pro/macbook-pro-mid-2014-xorosho-no-malo.html': '29 июля 2014 года обновилась вся линейка MacBook Pro. Как и все обновления с начала этого года, это тоже было незначительным. Что-то подобное уже было, в сам...',
              'appleinsider.ru/accessories/prezentaciya-apple-watch-polet-na-lunu-i-drugie-istorii.html': 'Это случилось 9 сентября 2014 года, в Купертино, в театре De Anza College, известном как Flint Center. Именно здесь Стив представил самый первый Mac 24 январ...',
              'appleinsider.ru/sudy-i-skandaly/huawei-propagandists.html': 'Бойкот, который китайские пользователи объявили Apple с целью поддержки Huawei, оказался довольно масштабным. По крайней мере, теперь все местные площадки пе...',
              'appleinsider.ru/sudy-i-skandaly/na-tima-kuka-podali-v-sud-za-obman-investorov.html': 'На Apple постоянно подают в суд. Но если одни делают это исключительно с целью заработать, ведь за выигрыш дела обычно полагается компенсация для пострадавше...',
              'appleinsider.ru/accessories/eto-samyj-treshovyj-aksessuar-dlya-iphone-kotoryj-my-videli.html': 'Ни один другой смартфон в мире не имеет такого широкого выбора аксессуаров, как iPhone. При этом совершенно неважно, моделью какого поколения вы пользуетесь ...',
              'appleinsider.ru/advert': '',
              'appleinsider.ru/about': '',
              'appleinsider.ru/podcastonair': '',
              'appleinsider.ru/discounts': ''}


description = [
{"appleinsider.ru/": "Обзор лучших приложений под iPhone, как отремонтировать iPhone или iPad, что нужно знать при покупке Mac и MacBook. Бесплатные приложения iOS и iPadOS."},
{"appleinsider.ru/page/38": "Обзор лучших приложений под iPhone, как отремонтировать iPhone или iPad, что нужно знать при покупке Mac и MacBook. Бесплатные приложения iOS и iPadOS."},
{"appleinsider.ru/page/180": "Обзор лучших приложений под iPhone, как отремонтировать iPhone или iPad, что нужно знать при покупке Mac и MacBook. Бесплатные приложения iOS и iPadOS."},
{"appleinsider.ru/page/8": "Обзор лучших приложений под iPhone, как отремонтировать iPhone или iPad, что нужно знать при покупке Mac и MacBook. Бесплатные приложения iOS и iPadOS."},
{"appleinsider.ru/iphone": "iPhone – это не просто телефон, а совершенно новый взгляд на жизнь. Именно благодаря ему вся индустрия смартфонов притерпела значительные изменения. На стран..."},
{"appleinsider.ru/iphone/page/5": "iPhone – это не просто телефон, а совершенно новый взгляд на жизнь. Именно благодаря ему вся индустрия смартфонов притерпела значительные изменения. На стран..."},
{"appleinsider.ru/accessories": "Для техники Apple в мире придуманы и продаются миллионы различных аксессуаров:  начиная от тряпочек для экрана, заканчивая золотыми чехлами. Но как выбрать  ..."},
{"appleinsider.ru/accessories/page/10": "Для техники Apple в мире придуманы и продаются миллионы различных аксессуаров:  начиная от тряпочек для экрана, заканчивая золотыми чехлами. Но как выбрать  ..."},
{"appleinsider.ru/ios": "Откройте для себя целую вселенную iOS благодаря нашим свежим новостям и интересным обзорам! Ни одно обновление этой мобильной платформы не пройдет мимо вашег..."},
{"appleinsider.ru/ios/page/30": "Откройте для себя целую вселенную iOS благодаря нашим свежим новостям и интересным обзорам! Ни одно обновление этой мобильной платформы не пройдет мимо вашег..."},
{"appleinsider.ru/ipad": "Первое поколение планшетного компьютера Apple вышло в 2010 году. Сейчас уже представлено 7 поколение iPad, а также iPad Pro в двух версиях — с экраном ..."},
{"appleinsider.ru/ipad/page/80": "Первое поколение планшетного компьютера Apple вышло в 2010 году. Сейчас уже представлено 7 поколение iPad, а также iPad Pro в двух версиях — с экраном ..."},
{"appleinsider.ru/safari": "Стив Джобс называет браузер Safari лучшим браузером на планете. В этой рубрике мы не только пытаемся разобраться, прав он или ошибается, но также просто расс..."},
{"appleinsider.ru/safari/page/2": "Стив Джобс называет браузер Safari лучшим браузером на планете. В этой рубрике мы не только пытаемся разобраться, прав он или ошибается, но также просто расс..."},
{"appleinsider.ru/obzory-zheleza": "Если вам мало простой информации о том, как выглядят и что могут новые устройства, в этой рубрике мы предлагаем вам возможность подробно изучить функции и ха..."},
{"appleinsider.ru/obzory-zheleza/page/9": "Если вам мало простой информации о том, как выглядят и что могут новые устройства, в этой рубрике мы предлагаем вам возможность подробно изучить функции и ха..."},
{"appleinsider.ru/tag/prilozhenie": "В App Store регулярно появляются новые интересные приложения, о существовании многих вы даже не подозреваете. При этом ими могут пользоваться миллионы челове..."},
{"appleinsider.ru/tag/prilozhenie/page/18": "В App Store регулярно появляются новые интересные приложения, о существовании многих вы даже не подозреваете. При этом ими могут пользоваться миллионы челове..."},
{"appleinsider.ru/tag/kompaniya-apple": "Самая инновационная и дорогая компания мира. Apple производит iPhone, iPad, iMac, MacBook, AirPods, сервисы Apple TV+, Apple Arcade и много чего еще. Сегодня..."},
{"appleinsider.ru/tag/kompaniya-apple/page/3": "Самая инновационная и дорогая компания мира. Apple производит iPhone, iPad, iMac, MacBook, AirPods, сервисы Apple TV+, Apple Arcade и много чего еще. Сегодня..."},
{"appleinsider.ru/tag/texnologii": "На нашем сайте мы регулярно рассказываем о самых новых и интересных технологиях, которые разрабатывает и внедряет компания Apple. А иногда благодаря неожидан..."},
{"appleinsider.ru/tag/texnologii/page/48": "На нашем сайте мы регулярно рассказываем о самых новых и интересных технологиях, которые разрабатывает и внедряет компания Apple. А иногда благодаря неожидан..."},
{"appleinsider.ru/tag/perevod-biografii-stiva-dzhobsa": "Стив Джобс — один из величайших изобретателей в истории человечества. И его биография представляет интерес не только для тех, кто хочет узнать побольше..."},
{"appleinsider.ru/tag/twitter": "В 21 веке многие люди уже не представляют жизни без родного твиттера. А благодаря присутствию этой службы в мобильных устройствах, вы можете получать доступ ..."},
{"appleinsider.ru/author/ivfilon": "По образованию бухгалтер. Работал продавцом-консультантом в компьютерном отделе торговой сети МегаМакс. Там и познакомился с техникой Apple. С тех пор постоя..."},
# {"appleinsider.ru/author/gellert": "Несостоявшийся юрист, волею судеб и главного редактора оказавшийся в должности автора на AppleInsider.ru, а потом и AndroidInsider.ru. Искренне считает, что разбирается в технике Apple не хуже самого Тима Кука и очень радуется, когда главред называет его орлом. Обладает глубокими познаниями в вопросах защиты прав потребителей. Сотрудничает с Медиагруппой i10.ru с 2015 года. Увлечения: инвестиции, научпоп, авиация."},
# {"appleinsider.ru/author/gellert/page/8": "Несотоявшийся юрист, волею судеб и главного редактора оказавшийся в должности автора на AppleInsider.ru, а потом и AndroidInsider.ru. Искренне считает, что разбирается в технике Apple не хуже самого Тима Кука и очень радуется, когда главред называет его орлом. Обладает глубокими познаниями в вопросах защиты прав потребителей. Сотрудничает с Медиагруппой i10.ru с 2015 года. Увлечения: инвестиции, научпоп, авиация."},
# {"appleinsider.ru/author/svarogstin": "Осенью 1987 года познакомился с Mac’ом, год внедрял на предприятии IBM PC, в результате чего, с 1988 года и до настоящего времени симпатизирует Apple, Mac’ам и другим творениям этой компании, что бы с ними не происходило – потому что знает что другой такой компании не было и нет. \nС 1997 по 1999, будучи директором по программному обеспечению представительства Apple в России, имел возможность близко познакомиться с теми кто делал эту компанию чем-то особенным."},
# {"appleinsider.ru/author/appleinsider-ru": "Сотрудник Appleinsider.ru с 17 февраля 2012 по 01 апреля 2020. Опубликовал 3 984 материала"},
{"appleinsider.ru/mac-pro/apple-nachala-oficialnye-prodazhi-novogo-mac-pro-v-rossii.html": "Долгое время свежие новинки от Apple появлялись в России с ощутимым запозданием. До определённого момента российский рынок ни разу не входил в число стран пе..."},
{"appleinsider.ru/iphone/apple-poluchaet-66-vsex-deneg-rynka-smartfonov.html": "Может быть, Тим Кук далеко не так хорош в проектировании новых продуктов Apple, как Стив Джобс, но он хороший управленец, который прекрасно понимает, как при..."},
{"appleinsider.ru/eto-interesno/pochemu-ekrannyj-touch-id-eto-put-apple-k-innovaciyam.html": "Несмотря на то что Face ID – пожалуй, самый технологически продвинутый и одновременно удобный способ авторизации, которым только можно снабдить смартфон, мно..."},
{"appleinsider.ru/hardware/thunderbolt-4-protiv-usb-4-ostanetsya-tolko-odin.html": "Шоу бытовой электроники 2020 года (CES-2020) открылось 7 января в Лас-Вегасе. А перед его открытием, в воскресение, 6 января, в конференц-центре Мандалай Бей..."},
{"appleinsider.ru/apple-tv/o-kakix-osobennostyax-apple-tv-vy-prosto-obyazany-znat.html": "Неделю назад Apple запустила сервис Apple TV+ с эксклюзивными фильмами и сериалами собственного производства. Несмотря на грандиозность проекта, он, как это ..."},
{"appleinsider.ru/apple-v-licax/stiv-voznyak-rasskazal-pro-svoyo-lyubimoe-ustrojstvo-ot-apple.html": "Если подумать, то смартфон – это, пожалуй, единственное устройство, с которым большинство из нас ни за что не расстанется. Планшеты, смарт-часы, фитнес-брасл..."},
{"appleinsider.ru/apple-v-licax/eks-marketolog-macintosh-rasskazal-kak-uderzhatsya-na-rabote-v-apple.html": "Работу в передовой компании можно сравнить с марафонским забегом. Недостаточно просто показать себя успешным кандидатом на собеседовании. Не менее важно, пол..."},
{"appleinsider.ru/analysis/vazhnaya-funkciya-apple-watch-okazalas-bespoleznoj-dlya-mnogix-polzovatelej.html": "Несмотря на возможность принять входящий звонок прямо с Apple Watch, подавляющее большинство пользователей не делают этого, предпочитая часам телефон. Это сл..."},
{'appleinsider.ru/advert': ''},
{'appleinsider.ru/about': ''},
{'appleinsider.ru/discounts': ''}
]

title = [
{"appleinsider.ru/": "AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/page/38": "AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/page/180": "AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/page/8": "AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/iphone": "iPhone |  Обзоры, советы, бесплатные игры и приложения, как отремонтировать iPhone "},
{"appleinsider.ru/iphone/page/5": "iPhone |  Обзоры, советы, бесплатные игры и приложения, как отремонтировать iPhone , cтраница 5"},
{"appleinsider.ru/accessories": "Аксессуары | Обзоры аксессуаров Apple "},
{"appleinsider.ru/accessories/page/10": "Аксессуары | Обзоры аксессуаров Apple , cтраница 10"},
{"appleinsider.ru/ios": "iOS | Новости iOS"},
{"appleinsider.ru/ios/page/30": "iOS | Новости iOS, cтраница 30"},
{"appleinsider.ru/ipad": "iPad | - обзоры, цены, iPadOS, купить в России"},
{"appleinsider.ru/ipad/page/80": "iPad | - обзоры, цены, iPadOS, купить в России, cтраница 80"},
{"appleinsider.ru/safari": "Safari | браузер Safari для Windows и Mac OS, последние новости"},
{"appleinsider.ru/safari/page/2": "Safari | браузер Safari для Windows и Mac OS, последние новости, cтраница 2"},
{"appleinsider.ru/obzory-zheleza": "Обзоры железа | обзоры лучших гаджетов"},
{"appleinsider.ru/obzory-zheleza/page/9": "Обзоры железа | обзоры лучших гаджетов, cтраница 9"},
{"appleinsider.ru/tag/prilozhenie": "Приложения - для iPhone и iPad, программы для iOS, игры"},
{"appleinsider.ru/tag/prilozhenie/page/18": "Приложения - для iPhone и iPad, программы для iOS, игры, cтраница 18"},
{"appleinsider.ru/tag/kompaniya-apple": "Компания Apple - производит iPhone, iPad, MacBook, iMac, AirPods и другую премиальную технику"},
{"appleinsider.ru/tag/kompaniya-apple/page/3": "Компания Apple - производит iPhone, iPad, MacBook, iMac, AirPods и другую премиальную технику, cтраница 3"},
{"appleinsider.ru/tag/texnologii": "Технологии Технологии и инновации, внедрения и новые разработки"},
{"appleinsider.ru/tag/texnologii/page/48": "Технологии Технологии и инновации, внедрения и новые разработки, cтраница 48"},
{"appleinsider.ru/tag/perevod-biografii-stiva-dzhobsa": "Биография Стива Джобса Биография Стива Джобса: новые факты, подробности"},
{"appleinsider.ru/tag/twitter": "Twitter уникальный сервис микроблогов "},
{"appleinsider.ru/author/ivfilon": "Игорь Филон | AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/author/gellert": "Иван Кузнецов | AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/author/gellert/page/8": "Иван Кузнецов | AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/author/svarogstin": "Олег Свиргстин | AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/author/appleinsider-ru": "AppleInsider.ru | AppleInsider.ru — крупнейший сайт о iPhone, iPad, Mac в России"},
{"appleinsider.ru/mac-pro/apple-nachala-oficialnye-prodazhi-novogo-mac-pro-v-rossii.html": "Apple начала официальные продажи нового Mac Pro в России - AppleInsider.ru"},
{"appleinsider.ru/iphone/apple-poluchaet-66-vsex-deneg-rynka-smartfonov.html": "Apple получает 66% всех денег рынка смартфонов - AppleInsider.ru"},
{"appleinsider.ru/eto-interesno/pochemu-ekrannyj-touch-id-eto-put-apple-k-innovaciyam.html": "Почему экранный Touch ID — это путь Apple к инновациям - AppleInsider.ru"},
{"appleinsider.ru/hardware/thunderbolt-4-protiv-usb-4-ostanetsya-tolko-odin.html": "Thunderbolt 4 против USB 4: останется только один? - AppleInsider.ru"},
{"appleinsider.ru/apple-tv/o-kakix-osobennostyax-apple-tv-vy-prosto-obyazany-znat.html": "О каких особенностях Apple TV+ вы просто обязаны знать - AppleInsider.ru"},
{"appleinsider.ru/apple-v-licax/stiv-voznyak-rasskazal-pro-svoyo-lyubimoe-ustrojstvo-ot-apple.html": "Стив Возняк рассказал про своё любимое устройство от Apple - AppleInsider.ru"},
{"appleinsider.ru/apple-v-licax/eks-marketolog-macintosh-rasskazal-kak-uderzhatsya-na-rabote-v-apple.html": "Экс-маркетолог Macintosh рассказал, как удержаться на работе в Apple - AppleInsider.ru"},
{"appleinsider.ru/analysis/vazhnaya-funkciya-apple-watch-okazalas-bespoleznoj-dlya-mnogix-polzovatelej.html": "Важная функция Apple Watch оказалась бесполезной для многих пользователей - AppleInsider.ru"},
{"appleinsider.ru/advert": "Рекламодателям - AppleInsider.ru"},
{"appleinsider.ru/about": "О сайте - AppleInsider.ru"},
{"appleinsider.ru/discounts": "Скидочки - AppleInsider.ru"},
]