description = [
{"androidinsider.ru": "Настройка смарфтонов на Android, установка лучших бесплатных приложений, секреты и лайфхаки, которые помогут полностью настроить всё под себя."},
{"androidinsider.ru/page/8": "Настройка смарфтонов на Android, установка лучших бесплатных приложений, секреты и лайфхаки, которые помогут полностью настроить всё под себя."},
{"androidinsider.ru/page/38": "Настройка смарфтонов на Android, установка лучших бесплатных приложений, секреты и лайфхаки, которые помогут полностью настроить всё под себя."},
{"androidinsider.ru/page/180": "Настройка смарфтонов на Android, установка лучших бесплатных приложений, секреты и лайфхаки, которые помогут полностью настроить всё под себя."},
{"androidinsider.ru/novosti": "Самые свежие новости из мира Android."},
{"androidinsider.ru/novosti/page/5": "Самые свежие новости из мира Android."},
{"androidinsider.ru/soft": "Приложения бывают разные — разной категории, разной направленности и функциональности, даже разной полезности. Мы хотим, чтобы вы пользовались только х..."},
{"androidinsider.ru/soft/page/10": "Приложения бывают разные — разной категории, разной направленности и функциональности, даже разной полезности. Мы хотим, чтобы вы пользовались только х..."},
{"androidinsider.ru/smartfony": "То, что не выходит из наших рук в течение всего дня — это смартфон. Современные мобильные телефоны — это уже не просто телефоны, это те устройств..."},
{"androidinsider.ru/smartfony/page/30": "То, что не выходит из наших рук в течение всего дня — это смартфон. Современные мобильные телефоны — это уже не просто телефоны, это те устройств..."},
{"androidinsider.ru/obzory-prilozhenij": "Google Play полнится приложениями, играми, утилитками и прочими полезными штуками. Однако не все из них достойны того, чтобы обосноваться на наших устройства..."},
{"androidinsider.ru/obzory-prilozhenij/page/80": "Google Play полнится приложениями, играми, утилитками и прочими полезными штуками. Однако не все из них достойны того, чтобы обосноваться на наших устройства..."},
{"androidinsider.ru/eto-interesno": "В этой рубрике мы соберем для вас самые интересные новости, которые быть может и не совсем полностью относятся к миру мобильных технологий и IT, но все же до..."},
{"androidinsider.ru/eto-interesno/page/20": "В этой рубрике мы соберем для вас самые интересные новости, которые быть может и не совсем полностью относятся к миру мобильных технологий и IT, но все же до..."},
{"androidinsider.ru/polezno-znat": "Существует такое понятие — «лайфхак», означающее не всегда очевидную последовательность действий, которая в итоге так или иначе делает нашу ж..."},
{"androidinsider.ru/polezno-znat/page/9": "Существует такое понятие — «лайфхак», означающее не всегда очевидную последовательность действий, которая в итоге так или иначе делает нашу ж..."},
{"androidinsider.ru/tag/android": "Как настроить Android под себя, как включить ночную тему, как скачать приложения недоступные в Google Play, нужно ли ставить антивирусы, какой смартфон купит..."},
{"androidinsider.ru/tag/android/page/18": "Как настроить Android под себя, как включить ночную тему, как скачать приложения недоступные в Google Play, нужно ли ставить антивирусы, какой смартфон купит..."},
{"androidinsider.ru/tag/samsung": "Главный конкурент компании Apple. Samsung всегда отличалась введением в свои смартфоны самых передовых технических решений, материалов корпуса и программной ..."},
{"androidinsider.ru/tag/samsung/page/32": "Главный конкурент компании Apple. Samsung всегда отличалась введением в свои смартфоны самых передовых технических решений, материалов корпуса и программной ..."},
{"androidinsider.ru/tag/prilozhenija": "Как выбрать лучшие приложения для Android? Как сэкономить при покупке или вообще загрузить лучшие приложения бесплатно? Как выбрать среди сотен однотипных пр..."},
{"androidinsider.ru/tag/prilozhenija/page/48": "Как выбрать лучшие приложения для Android? Как сэкономить при покупке или вообще загрузить лучшие приложения бесплатно? Как выбрать среди сотен однотипных пр..."},
{"androidinsider.ru/tag/lg-g-watch": "LG G Watch — современный представитель категории носимой электроники, так называемые умные часы, первое изделие корейской компании на базе Android Wear, рабо..."},
{"androidinsider.ru/tag/nokia": "Некогда крутой бренд, которому мы во многом обязаны появлением связи как таковой и ее распространением. Проблема в том, что раньше это был крутой бренд, зада..."},
{"androidinsider.ru/author/Zellcer": "Сотрудник Androidinsider.ru с 20 января 2019 по 21 декабря 2019. Опубликовал 662 материала"},
# {"androidinsider.ru/author/gellert": "Несостоявшийся юрист, волею судеб и главного редактора оказавшийся в должности автора на AppleInsider.ru, а потом и AndroidInsider.ru. Искренне считает, что разбирается в Android не хуже самого Энди Рубина и очень радуется, когда главред называет его орлом. Главный по вопросам защиты прав потребителей. Сотрудничает с Медиагруппой i10.ru с 2015 года. Увлечения: инвестиции, научпоп, авиация."},
# {"androidinsider.ru/author/AndroidInsider.ru": ""},
{"androidinsider.ru/author/Slawian4ik": "Люблю ковыряться в гаджетах сколько себя помню. С Android познакомился на Samsung Galaxy S 2. С тех пор активно копаюсь в прошивках и оболочках. В железе тож..."},
{"androidinsider.ru/novosti/tainstvennyj-smartfon-linejki-iz-oneplus-pokazhut-v-yanvare.html": "Вне всяких сомнений, одними из главных игроков на рынке смартфонов в уходящем 2019 году оказались Google и Samsung со своими флагманами Pixel 4\\4XL и Galaxy ..."},
{"androidinsider.ru/polezno-znat/pochemu-kamera-na-108-megapikselej-ne-nuzhna.html": "В 2019 год несколько крупных игроков рынка мобильных устройств, включая Apple, Samsung и Google, по-прежнему используют камеры на 12 мегапикселей в своих фла..."},
{"androidinsider.ru/obzory-prilozhenij/kak-sdelat-ikonki-na-android-kvadratnymi.html": "Если раньше еще можно было спорить о том, что круче в плане внешнего вида операционной системы - Android или iOS, то сейчас обе \"оси\" выглядят одинаково хоро..."},
{"androidinsider.ru/polezno-znat/google-hochet-zapretit-ustanovku-apk-na-android.html": "Одной из возможностей операционной системы Android, которая, по мнению пользователей, выгодно отличает её от iOS, является возможность установки приложений в..."},
{"androidinsider.ru/obzory-prilozhenij/chto-takoe-binauralnyj-zvuk-i-pochemu-vam-stoit-poprobovat-etu-tehnologiyu-na-svoem-smartfone.html": "Физика и физиология - это две удивительные ветви науки, которые могут помочь узнать нам много всего нового об окружающем мире и о нас самих. Но если они вдру..."},
{"androidinsider.ru/soft/google-dobavila-v-google-foto-chat-dlya-obmena-fotografiyami.html": "«Google Фото» явно не из тех приложений, которые часто получают обновления с новыми функциями, но уж если Google и решает выпустить для облачного хранилища с..."},
{"androidinsider.ru/novosti/dejstivtelno-li-temnaya-tema-prodlevaet-vremya-raboty-batarei.html": "В последнее время темная тема для смартфонов находится, что называется, \"на хайпе\". При этом помимо того, что тема эта выглядит весьма стильно и свежо, она и..."},
{"androidinsider.ru/smartfony/nekotorye-banki-zapretili-ustanavlivat-svoi-prilozheniya-na-galaxy-s10.html": "Ситуации, когда разработчики приложений добровольно отказываются от поддержки конкретных моделей смартфонов, возникают чрезвычайно редко. Если это и происход..."}
]


title = [
{"androidinsider.ru": "AndroidInsider.ru - если у вас смартфон на Android, то вам сюда"},
{"androidinsider.ru/page/8": "AndroidInsider.ru - если у вас смартфон на Android, то вам сюда"},
{"androidinsider.ru/page/38": "AndroidInsider.ru - если у вас смартфон на Android, то вам сюда"},
{"androidinsider.ru/page/180": "AndroidInsider.ru - если у вас смартфон на Android, то вам сюда"},
{"androidinsider.ru/novosti": "Новости  - AndroidInsider.ru"},
{"androidinsider.ru/novosti/page/5": "Новости  - AndroidInsider.ru"},
{"androidinsider.ru/soft": "Софт на android: лучшие бесплатные и платные приложения - AndroidInsider.ru"},
{"androidinsider.ru/soft/page/10": "Софт на android: лучшие бесплатные и платные приложения - AndroidInsider.ru"},
{"androidinsider.ru/smartfony": "Смартфоны Обзоры Android смартфонов - AndroidInsider.ru"},
{"androidinsider.ru/smartfony/page/30": "Смартфоны Обзоры Android смартфонов - AndroidInsider.ru"},
{"androidinsider.ru/obzory-prilozhenij": "Обзоры приложений Обзоры Android приложений: системных, игровых, бесплатных и платных - AndroidInsider.ru"},
{"androidinsider.ru/obzory-prilozhenij/page/80": "Обзоры приложений Обзоры Android приложений: системных, игровых, бесплатных и платных - AndroidInsider.ru"},
{"androidinsider.ru/eto-interesno": "Это интересно интересные и актуальные новости в сфере android устройств - AndroidInsider.ru"},
{"androidinsider.ru/eto-interesno/page/20": "Это интересно интересные и актуальные новости в сфере android устройств - AndroidInsider.ru"},
{"androidinsider.ru/polezno-znat": "Полезно знать Интересные фишки и полезные хитрости для android устройств - AndroidInsider.ru"},
{"androidinsider.ru/polezno-znat/page/9": "Полезно знать Интересные фишки и полезные хитрости для android устройств - AndroidInsider.ru"},
{"androidinsider.ru/tag/android": "Android обзор операционной системы, лайфхаки, настройки, темы, виджеты - AndroidInsider.ru"},
{"androidinsider.ru/tag/android/page/18": "Android обзор операционной системы, лайфхаки, настройки, темы, виджеты - AndroidInsider.ru"},
{"androidinsider.ru/tag/samsung": "Смартфоны Samsung - Galaxy S20, S20 Plus, S20 Ultra, S10, Samsung A-серии. Обзоры, сравнения, что купить - AndroidInsider.ru"},
{"androidinsider.ru/tag/samsung/page/32": "Смартфоны Samsung - Galaxy S20, S20 Plus, S20 Ultra, S10, Samsung A-серии. Обзоры, сравнения, что купить - AndroidInsider.ru"},
{"androidinsider.ru/tag/prilozhenija": "Приложения - обзоры из Google Play, со скидкой, временно бесплатные, лучшие в своей категории - AndroidInsider.ru"},
{"androidinsider.ru/tag/prilozhenija/page/48": "Приложения - обзоры из Google Play, со скидкой, временно бесплатные, лучшие в своей категории - AndroidInsider.ru"},
{"androidinsider.ru/tag/lg-g-watch": "LG G Watch - умные часы: обзор, отзывы и видео смарт часов от LG - AndroidInsider.ru"},
{"androidinsider.ru/tag/nokia": "Смартфоны Nokia  - обзоры, технические характеристики, новости, сравнения, трюки, советы - AndroidInsider.ru"},
{"androidinsider.ru/author/Zellcer": "Владимир Кузнецов - AndroidInsider.ru"},
{"androidinsider.ru/author/gellert": "Иван Кузнецов - AndroidInsider.ru"},
{"androidinsider.ru/author/AndroidInsider.ru": "AndroidInsider.ru - AndroidInsider.ru"},
{"androidinsider.ru/author/Slawian4ik": "Вячеслав Ларионов - AndroidInsider.ru"},
{"androidinsider.ru/novosti/tainstvennyj-smartfon-linejki-iz-oneplus-pokazhut-v-yanvare.html": "Таинственный смартфон из линейки OnePlus покажут в январе - AndroidInsider.ru"},
{"androidinsider.ru/polezno-znat/pochemu-kamera-na-108-megapikselej-ne-nuzhna.html": "Почему камера на 108 мегапикселей не нужна - AndroidInsider.ru"},
{"androidinsider.ru/obzory-prilozhenij/kak-sdelat-ikonki-na-android-kvadratnymi.html": "Как сделать иконки на Android квадратными - AndroidInsider.ru"},
{"androidinsider.ru/polezno-znat/google-hochet-zapretit-ustanovku-apk-na-android.html": "Google хочет запретить установку APK на Android - AndroidInsider.ru"},
{"androidinsider.ru/obzory-prilozhenij/chto-takoe-binauralnyj-zvuk-i-pochemu-vam-stoit-poprobovat-etu-tehnologiyu-na-svoem-smartfone.html": "Что такое бинауральный звук и почему вам стоит попробовать эту технологию на своем смартфоне - AndroidInsider.ru"},
{"androidinsider.ru/soft/google-dobavila-v-google-foto-chat-dlya-obmena-fotografiyami.html": "Google добавила в «Google Фото» чат для обмена фотографиями - AndroidInsider.ru"},
{"androidinsider.ru/novosti/dejstivtelno-li-temnaya-tema-prodlevaet-vremya-raboty-batarei.html": "Действительно ли темная тема продлевает время работы батареи? - AndroidInsider.ru"},
{"androidinsider.ru/smartfony/nekotorye-banki-zapretili-ustanavlivat-svoi-prilozheniya-na-galaxy-s10.html": "Некоторые банки запретили устанавливать свои приложения на Galaxy S10 - AndroidInsider.ru"},
]